"""create storage tables

Revision ID: 2072f4778f93
Revises: 
Create Date: 2025-12-11 12:18:08.680265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2072f4778f93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agsi_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gas_in_storage_gwh', sa.Float(), nullable=True),
    sa.Column('injection', sa.Float(), nullable=True),
    sa.Column('withdrawal', sa.Float(), nullable=True),
    sa.Column('working_gas_gwh', sa.Float(), nullable=True),
    sa.Column('full_pct', sa.Float(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_agsi_timeseries_date'), 'agsi_timeseries', ['date'], unique=False, schema='public')
    op.create_table('alsi_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lng_storage_gwh', sa.Float(), nullable=True),
    sa.Column('sendOut', sa.Float(), nullable=True),
    sa.Column('dtmi_gwh', sa.Float(), nullable=True),
    sa.Column('dtrs', sa.Float(), nullable=True),
    sa.Column('contractedCapacity', sa.Float(), nullable=True),
    sa.Column('availableCapacity', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_alsi_timeseries_date'), 'alsi_timeseries', ['date'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_alsi_timeseries_date'), table_name='alsi_timeseries', schema='public')
    op.drop_table('alsi_timeseries', schema='public')
    op.drop_index(op.f('ix_public_agsi_timeseries_date'), table_name='agsi_timeseries', schema='public')
    op.drop_table('agsi_timeseries', schema='public')
    # ### end Alembic commands ###
